import { StyleSheet } from "react-native";
import { appTheme } from "../theme/designSystem";

export const styles = StyleSheet.create({
  screenContent: {
    flex: 1,
    paddingHorizontal: appTheme.spacing.lg,
    paddingTop: appTheme.spacing.lg,
    paddingBottom: appTheme.spacing.sm,
    gap: appTheme.spacing.lg,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    gap: appTheme.spacing.md,
  },
  menuButton: {
    width: 42,
    height: 42,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
  },
  topBarText: {
    flex: 1,
  },
  topBarTitle: {
    ...appTheme.typography.headingSmall,
    color: appTheme.colors.textPrimary,
  },
  topBarSubtitle: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
  },
  autoSpeakButton: {
    width: 40,
    height: 40,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
  },
  autoSpeakButtonActive: {
    backgroundColor: appTheme.colors.primary,
    borderColor: appTheme.colors.primary,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: appTheme.colors.card,
    borderRadius: appTheme.radii.lg,
    padding: appTheme.spacing.xl,
    gap: appTheme.spacing.sm,
    ...appTheme.shadows.card,
  },
  headerTextWrap: {
    flex: 1,
  },
  title: {
    ...appTheme.typography.headingMedium,
    color: appTheme.colors.textPrimary,
  },
  subtitle: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
  },
  voiceToggleButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: appTheme.spacing.xs,
    paddingHorizontal: appTheme.spacing.md,
    paddingVertical: appTheme.spacing.sm,
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.background,
  },
  voiceToggleText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textPrimary,
    fontWeight: "600",
  },
  signalsCard: {
    backgroundColor: appTheme.colors.cardTinted,
    borderRadius: appTheme.radii.lg,
    padding: appTheme.spacing.lg,
    gap: appTheme.spacing.sm,
    ...appTheme.shadows.card,
  },
  signalText: {
    alignSelf: "flex-start",
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.primaryLight,
    paddingHorizontal: appTheme.spacing.md,
    paddingVertical: appTheme.spacing.xs,
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.primary,
    fontWeight: "500",
  },
  quickPromptRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: appTheme.spacing.sm,
  },
  quickPromptChip: {
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.subtlePressed,
    paddingHorizontal: appTheme.spacing.lg,
    paddingVertical: appTheme.spacing.sm,
  },
  quickPromptChipDisabled: {
    opacity: 0.45,
  },
  quickPromptText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.primary,
    fontWeight: "600",
  },
  chatScroll: {
    flex: 1,
  },
  chatContent: {
    paddingVertical: appTheme.spacing.md,
    gap: appTheme.spacing.lg,
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    gap: appTheme.spacing.xl,
    paddingBottom: appTheme.spacing.xxl,
  },
  emptyHeroText: {
    alignItems: "center",
    gap: appTheme.spacing.sm,
    paddingHorizontal: appTheme.spacing.md,
  },
  emptyTitle: {
    ...appTheme.typography.headingLarge,
    color: appTheme.colors.textPrimary,
    fontWeight: "800",
    textAlign: "center",
  },
  emptySubtitle: {
    ...appTheme.typography.headingSmall,
    color: appTheme.colors.textPrimary,
    textAlign: "center",
  },
  emptyHelper: {
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.textSecondary,
    textAlign: "center",
  },
  messageRow: {
    width: "100%",
  },
  assistantRow: {
    alignItems: "flex-start",
  },
  userRow: {
    alignItems: "flex-end",
  },
  messageBubble: {
    borderRadius: appTheme.radii.lg,
    paddingHorizontal: appTheme.spacing.lg,
    paddingVertical: appTheme.spacing.md,
    gap: appTheme.spacing.sm,
  },
  assistantBubble: {
    maxWidth: "85%",
    backgroundColor: appTheme.colors.card,
    ...appTheme.shadows.card,
  },
  userBubble: {
    maxWidth: "75%",
    backgroundColor: appTheme.colors.primary,
  },
  messageText: {
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.textPrimary,
  },
  userMessageText: {
    color: appTheme.colors.onPrimary,
  },
  workoutCard: {
    maxWidth: "85%",
    borderRadius: appTheme.radii.lg,
    backgroundColor: appTheme.colors.card,
    padding: appTheme.spacing.lg,
    gap: appTheme.spacing.md,
    ...appTheme.shadows.card,
  },
  workoutCardHeader: {
    gap: appTheme.spacing.xs,
  },
  workoutCardEyebrow: {
    ...appTheme.typography.label,
    color: appTheme.colors.primary,
  },
  workoutCardTitle: {
    ...appTheme.typography.headingSmall,
    color: appTheme.colors.textPrimary,
  },
  workoutCardSubtitle: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
  },
  workoutExerciseList: {
    gap: appTheme.spacing.sm,
    backgroundColor: appTheme.colors.cardTinted,
    borderRadius: appTheme.radii.md,
    padding: appTheme.spacing.md,
  },
  workoutExerciseRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: appTheme.spacing.sm,
    paddingBottom: appTheme.spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: appTheme.colors.border,
  },
  workoutExerciseName: {
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.textPrimary,
    flex: 1,
  },
  workoutExerciseMeta: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
    fontWeight: "600",
  },
  mealPlanRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: appTheme.spacing.md,
    paddingBottom: appTheme.spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: appTheme.colors.border,
  },
  mealPlanTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: appTheme.spacing.xs,
  },
  mealLogButton: {
    minWidth: 58,
    minHeight: 36,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.background,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
    paddingHorizontal: appTheme.spacing.md,
  },
  mealLogButtonDisabled: {
    opacity: 0.45,
  },
  mealLogButtonText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.primary,
    fontWeight: "700",
  },
  workoutCardFooter: {
    marginTop: appTheme.spacing.xs,
  },
  speakMessageButton: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: appTheme.spacing.xs,
    paddingHorizontal: appTheme.spacing.sm,
    paddingVertical: appTheme.spacing.xs,
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.background,
  },
  speakMessageButtonText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
    fontWeight: "500",
  },
  thinkingBubble: {
    flexDirection: "row",
    alignItems: "center",
    gap: appTheme.spacing.sm,
  },
  thinkingText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
  },
  composerWrap: {
    backgroundColor: appTheme.colors.card,
    borderTopWidth: 1,
    borderTopColor: appTheme.colors.border,
    padding: appTheme.spacing.md,
    gap: appTheme.spacing.sm,
    marginHorizontal: -appTheme.spacing.lg,
    marginBottom: 0,
    paddingBottom: appTheme.spacing.sm,
  },  
  composerWrapCentered: {
    borderTopWidth: 0,
    borderRadius: appTheme.radii.lg,
    marginHorizontal: 0,
    padding: appTheme.spacing.md,
    ...appTheme.shadows.card,
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "flex-end",
    gap: appTheme.spacing.sm,
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.background,
  },
  iconButtonActive: {
    backgroundColor: appTheme.colors.danger,
  },
  input: {
    flex: 1,
    minHeight: 38,
    maxHeight: 120,
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.background,
    paddingHorizontal: appTheme.spacing.lg,
    paddingVertical: appTheme.spacing.sm,
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.textPrimary,
    textAlignVertical: "top",
  },
  sendButton: {
    width: 38,
    height: 38,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.primary,
  },
  sendButtonDisabled: {
    backgroundColor: appTheme.colors.subtlePressed,
  },
  statusText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
    paddingHorizontal: appTheme.spacing.xs,
  },
  sidebarModalRoot: {
    flex: 1,
    paddingTop : appTheme.spacing.xxl,
  },
  sidebarOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: appTheme.colors.overlay,
  },
  sidebarPanel: {
    width: 312,
    maxWidth: "86%",
    height: "100%",
    backgroundColor: appTheme.colors.background,
    borderRightWidth: 1,
    borderRightColor: appTheme.colors.border,
    paddingHorizontal: appTheme.spacing.lg,
    paddingTop: appTheme.spacing.xxl,
    paddingBottom: appTheme.spacing.lg,
    gap: appTheme.spacing.lg,
    ...appTheme.shadows.modal,
  },
  sidebarHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: appTheme.spacing.md,
  },
  sidebarTitle: {
    ...appTheme.typography.headingMedium,
    color: appTheme.colors.textPrimary,
  },
  sidebarSubtitle: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
    maxWidth: 220,
  },
  sidebarCloseButton: {
    width: 34,
    height: 34,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.card,
  },
  newChatButton: {
    minHeight: 42,
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.primary,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: appTheme.spacing.sm,
    paddingHorizontal: appTheme.spacing.lg,
  },
  newChatButtonText: {
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.onPrimary,
    fontWeight: "700",
  },
  sidebarState: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    gap: appTheme.spacing.md,
    paddingHorizontal: appTheme.spacing.md,
  },
  sidebarSkeletonList: {
    flex: 1,
    gap: appTheme.spacing.sm,
  },
  sidebarSkeletonItem: {
    borderRadius: appTheme.radii.md,
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
    paddingHorizontal: appTheme.spacing.md,
    paddingVertical: appTheme.spacing.md,
    gap: appTheme.spacing.xs,
  },
  sidebarStateText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
    textAlign: "center",
  },
  retryButton: {
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
    paddingHorizontal: appTheme.spacing.lg,
    paddingVertical: appTheme.spacing.sm,
  },
  retryButtonText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textPrimary,
    fontWeight: "600",
  },
  conversationList: {
    flex: 1,
  },
  conversationListContent: {
    gap: appTheme.spacing.sm,
    paddingBottom: appTheme.spacing.lg,
  },
  conversationItem: {
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
    borderRadius: appTheme.radii.md,
    flexDirection: "row",
    alignItems: "center",
    gap: appTheme.spacing.sm,
    paddingLeft: appTheme.spacing.md,
    paddingVertical: appTheme.spacing.md,
    paddingRight: appTheme.spacing.sm,
  },
  conversationItemActive: {
    borderColor: appTheme.colors.primary,
    backgroundColor: appTheme.colors.cardTinted,
  },
  conversationItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: appTheme.spacing.sm,
  },
  conversationOpenArea: {
    flex: 1,
    gap: appTheme.spacing.xs,
    minWidth: 0,
  },
  conversationDeleteButton: {
    width: 36,
    height: 36,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.background,
  },
  conversationTitle: {
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.textPrimary,
    fontWeight: "700",
    flex: 1,
  },
  conversationTitleActive: {
    color: appTheme.colors.primary,
  },
  conversationDate: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textMuted,
  },
  conversationPreview: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
  },
});
