import { StyleSheet } from "react-native";
import { appTheme } from "../theme/designSystem";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: appTheme.colors.background,
  },
  backgroundLayer: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: appTheme.colors.background,
    overflow: "hidden",
  },
  glow: {
    position: "absolute",
    borderRadius: 999,
    opacity: 0.78,
  },
  glowMint: {
    width: 260,
    height: 260,
    left: -110,
    top: 84,
    backgroundColor: "rgba(34, 197, 94, 0.2)",
  },
  glowBlue: {
    width: 320,
    height: 320,
    right: -150,
    top: 180,
    backgroundColor: "rgba(6, 182, 212, 0.18)",
  },
  glowViolet: {
    width: 280,
    height: 280,
    left: 42,
    bottom: -140,
    backgroundColor: "rgba(139, 92, 246, 0.14)",
  },
  horizonLight: {
    position: "absolute",
    left: appTheme.spacing.lg,
    right: appTheme.spacing.lg,
    top: 418,
    height: 1,
    backgroundColor: appTheme.colors.border,
  },
  scrollContent: {
    paddingHorizontal: appTheme.spacing.lg,
    paddingTop: appTheme.spacing.lg,
    paddingBottom: appTheme.spacing.xxl + appTheme.spacing.lg,
    gap: appTheme.spacing.xxl,
  },
  heroSection: {
    minHeight: 650,
    alignItems: "center",
    justifyContent: "center",
    gap: appTheme.spacing.lg,
  },
  brandPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: appTheme.spacing.sm,
    paddingHorizontal: appTheme.spacing.lg,
    paddingVertical: appTheme.spacing.sm,
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.primaryLight,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
  },
  brandPillText: {
    ...appTheme.typography.label,
    color: appTheme.colors.primary,
  },
  title: {
    color: appTheme.colors.textPrimary,
    fontSize: 32,
    lineHeight: 38,
    fontWeight: "800",
    letterSpacing: 0,
    textAlign: "center",
    maxWidth: 390,
  },
  subtitle: {
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.textSecondary,
    textAlign: "center",
    maxWidth: 360,
  },
  heroVisual: {
    width: "100%",
    height: 326,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: appTheme.spacing.sm,
  },
  heroHalo: {
    position: "absolute",
    width: 286,
    height: 286,
    borderRadius: 143,
    backgroundColor: "rgba(31, 41, 55, 0.86)",
    borderWidth: 1,
    borderColor: appTheme.colors.border,
    shadowColor: appTheme.colors.primary,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.12,
    shadowRadius: 28,
    elevation: 4,
  },
  visualCore: {
    width: 304,
    height: 304,
  },
  orbitCard: {
    position: "absolute",
    width: 116,
    minHeight: 84,
    justifyContent: "center",
    gap: appTheme.spacing.xs,
    padding: appTheme.spacing.md,
    borderRadius: appTheme.radii.lg,
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
    ...appTheme.shadows.card,
  },
  orbitCardLeft: {
    left: 4,
    top: 76,
  },
  orbitCardRight: {
    right: 4,
    bottom: 58,
  },
  orbitLabel: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
  },
  orbitValue: {
    ...appTheme.typography.headingSmall,
    color: appTheme.colors.textPrimary,
  },
  identityRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: appTheme.spacing.sm,
  },
  identityChip: {
    paddingHorizontal: appTheme.spacing.lg,
    paddingVertical: appTheme.spacing.sm,
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
  },
  identityText: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.primary,
    fontWeight: "600",
  },
  ctaRow: {
    width: "100%",
    gap: appTheme.spacing.md,
    marginTop: appTheme.spacing.sm,
  },
  primaryCta: {
    minHeight: appTheme.sizes.buttonMinHeight,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.primary,
    ...appTheme.shadows.card,
  },
  primaryCtaText: {
    color: appTheme.colors.onPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
  },
  secondaryCta: {
    minHeight: appTheme.sizes.buttonMinHeight,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: appTheme.radii.pill,
    backgroundColor: appTheme.colors.card,
    borderWidth: 1.5,
    borderColor: appTheme.colors.border,
  },
  secondaryCtaText: {
    color: appTheme.colors.primary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: "700",
  },
  storySection: {
    gap: appTheme.spacing.lg,
  },
  sectionHeader: {
    gap: appTheme.spacing.sm,
  },
  sectionEyebrow: {
    ...appTheme.typography.label,
    color: appTheme.colors.primary,
  },
  sectionTitle: {
    ...appTheme.typography.headingLarge,
    color: appTheme.colors.textPrimary,
  },
  capabilityGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: appTheme.spacing.md,
  },
  capabilityCard: {
    width: "48%",
    minHeight: 162,
    gap: appTheme.spacing.sm,
    padding: appTheme.spacing.lg,
    borderRadius: appTheme.radii.lg,
    backgroundColor: appTheme.colors.card,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
    ...appTheme.shadows.card,
  },
  capabilityIcon: {
    width: 38,
    height: 38,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.primary,
  },
  capabilityTitle: {
    ...appTheme.typography.headingSmall,
    color: appTheme.colors.textPrimary,
  },
  capabilityCopy: {
    ...appTheme.typography.bodySmall,
    color: appTheme.colors.textSecondary,
  },
  coachPanel: {
    alignItems: "center",
    gap: appTheme.spacing.md,
    paddingHorizontal: appTheme.spacing.xl,
    paddingVertical: appTheme.spacing.xxl,
    borderRadius: appTheme.radii.xl,
    backgroundColor: appTheme.colors.cardTinted,
    borderWidth: 1,
    borderColor: appTheme.colors.border,
  },
  coachOrb: {
    width: 54,
    height: 54,
    borderRadius: appTheme.radii.pill,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: appTheme.colors.card,
    ...appTheme.shadows.card,
  },
  coachTitle: {
    ...appTheme.typography.headingLarge,
    color: appTheme.colors.textPrimary,
    textAlign: "center",
  },
  coachCopy: {
    ...appTheme.typography.bodyLarge,
    color: appTheme.colors.textSecondary,
    textAlign: "center",
  },
  authSection: {
    gap: appTheme.spacing.md,
  },
  authEyebrow: {
    ...appTheme.typography.label,
    color: appTheme.colors.primary,
    textAlign: "center",
  },
  authTitle: {
    ...appTheme.typography.headingMedium,
    color: appTheme.colors.textPrimary,
    textAlign: "center",
    marginBottom: appTheme.spacing.xs,
  },
  authLoadingSkeletonRow: {
    gap: appTheme.spacing.sm,
    alignItems: "center",
    marginTop: appTheme.spacing.xs,
  },
});
