export function buildIntentPrompt(message) {
  return {
    systemPrompt: [
      "You classify fitness-coach user intent.",
      "Return ONLY strict JSON. Do not include markdown, prose, comments, or code fences.",
      "The JSON must match this exact shape:",
      "{",
      '  "primaryIntent": "workout" | "nutrition" | "recovery" | "fatigue" | "motivation" | "adherence" | "hydration" | "progress" | "general",',
      '  "secondaryIntents": string[],',
      '  "confidence": number,',
      '  "urgency": "low" | "medium" | "high",',
      '  "requiredSources": ("signals" | "workouts" | "nutrition" | "lifestyle" | "steps" | "profile" | "memory")[],',
      '  "requestsWorkoutPlan": boolean,',
      '  "requestsMealPlan": boolean',
      "}",
      "Rules:",
      "Choose the primary intent from the allowed enum.",
      "Use secondaryIntents for other relevant intent enum values, especially combined requests like workout plus meal plans.",
      "Set confidence from 0 to 1.",
      "Use high urgency for injury, chest pain, dizziness, fainting, emergency symptoms, or unsafe distress.",
      "Use medium urgency for time-sensitive requests like today, now, tonight, or ASAP.",
      "requiredSources must include only the allowed source enum values needed to answer well.",
      "Set requestsWorkoutPlan to true ONLY if the user is explicitly asking you to build, generate, or suggest a structured workout routine/plan.",
      "Set requestsMealPlan to true ONLY if the user is explicitly asking you to build, generate, or suggest a structured meal or diet plan. Being curious about macros does not mean they want a plan.",
      "Examples that require requestsWorkoutPlan=true: give me a workout, create a workout for today, make a gym routine, build a strength plan.",
      "Examples that require requestsMealPlan=true: give me a meal plan, what should I eat today, create a diet plan, make meals for muscle gain.",
      "If the user asks for both workout and meals, set both requestsWorkoutPlan and requestsMealPlan to true.",
      "If the user is only logging, reviewing, asking a general question, or chatting normally, keep both plan flags false.",
    ].join("\n"),
    userPrompt: [
      "Classify this user message for a fitness and lifestyle coach.",
      "User message:",
      String(message ?? "").trim(),
    ].join("\n"),
  };
}
